In [1]:
import numpy as np #numpy kütüphanesi np takma adı il projeye dahil adiyoruz

In [5]:
dizi=np.full((4,3),5) #4 sütunluk 3hücreli 5 yazıyor
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [6]:
#yeni bir numpy dizisi oluşturuyoruz
np.array([1,2,3])

array([1, 2, 3])

In [7]:
#oluşturduğumuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])

In [8]:
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [9]:
dizi=np.array([1,2,3])

In [10]:
dizi=np.array([1,2,3.14])

In [11]:
dizi.dtype #dizinin değişken türünü verir. Numpy dizilerinde elemanların hepsi aynı türdedir 

dtype('float64')

In [13]:
dizi=np.array([1,2,3.14],dtype=int)
dizi
#3.14'ü ondalıklı sayıyı tam sayıyya çevirir

array([1, 2, 3])

In [22]:
#5 satır 7 sütünden oluşan rastgele sayılardan oluşan int türünd bir dizi oluştur
dizi=np.random.randint(0,10,(5,7),dtype=int)
dizi

array([[8, 5, 7, 8, 6, 1, 7],
       [1, 9, 4, 2, 5, 0, 0],
       [9, 1, 0, 3, 8, 6, 3],
       [2, 8, 9, 6, 4, 5, 8],
       [5, 7, 0, 2, 5, 6, 0]])

In [25]:
#bir boyutlu dizi oluşturma
birboyut=np.array([1,2,3,4])
#iki boyutlu dizi oluşturma
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [26]:
birboyut

array([1, 2, 3, 4])

In [27]:
ikiboyut

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:
np.zeros(7) #7 sıfırdan oluşan tek boyutlu dizi oluşturur

array([0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,3),dtype=int) # sıfırdan oluşan 2 boyutlu int dizi oluşturur

array([[0, 0, 0],
       [0, 0, 0]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.full((4,3),5) # 5 sayısından oluşan 2*3'lük dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [36]:
np.arange(2,22,5) # başlangıç ve bitiş artış değerine göre dizi oluşturma

array([ 2,  7, 12, 17])

In [38]:
np.linspace(2,10,num=7) #başlangıç ve bitiş değeri aralığında beiltilen miktarda eşit aralık

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [39]:
np.random.randint(0,10,(5,2)) # 0-10 aralığında 5*2 rastgele sayıdan oluşan 2 boyutlu dizi

array([[3, 3],
       [7, 5],
       [0, 0],
       [6, 9],
       [2, 1]])

In [40]:
#dizilerin eleman sayısını öğrenmek için shape komutu kullanılır
diz=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(5, 7)

In [41]:
#ndim dizi boyutunu öğrenmek için kullanılır
diz.ndim

2

In [42]:
#size dizideki toplam eleman sayısını gösterir
dizi.size

35

In [43]:
dizi.itemsize #dizideki her bir elemanın bayt cinsinen değerini 

4