In [5]:
import numpy as np # NumPy kütüphanesi genellikle np takma adı ile kullanılır
np.array([1,2,3]) # : NumPy dizisi oluşturmak için

array([1, 2, 3])

In [6]:
a=np.array([1,2,3]) #  Bir NumPy dizisini atama işlemi için

In [10]:
dizi=np.array([1,2,3,3.14])  # dizi içine eklenen bir ondalık sayı, tam sayı olan diğer elemanları da ondalık sayı ekliyor
dizi

array([1.  , 2.  , 3.  , 3.14])

In [11]:
dizi=np.array([1,2,3,3.14],dtype=int) # NumPy dizilerini tanımlama sırasında dizideki tüm elemanları tek tipe dönüştürme işlemi
# gerçekleştirebilir int eklendiği için ondalıklı sayıları saymıyo 
dizi

array([1, 2, 3, 3])

In [12]:
birboyut=np.array([1,2,3]) # NumPy kütüphanesini import ettikten sonra yandaki kodları yazarak bir boyutlu dizi
oluşturunuz.
birboyut

array([1, 2, 3])

In [13]:
ikiboyut = np.array([[1,2,3], [4,5,6]]) # İki boyutlu dizi oluşturmak için yandaki kodlamaları
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
ucboyut= np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])  # Üç boyutlu dizi oluşturmak için yandaki kodlamaları
ucboyut

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])